Random testing using config=Config(noExceptionMatch=False, generalize=False, localize=False, speed='FAST', probs='locsample.probs', LOCBaseline=0.2, noAlphaConvert=False, replayable=False, essentials=False, noCoverageExploit=False, quickTests=False, html=None, keepLast=False, stopWhenNoCoverage=None, generateLOC=None, computeFeatureStats=False, Pmutate=0.0, timeout=60, output='failure.13887.test', markov=None, noSwarmDependencies=False, startExploit=0.0, maxMustHitBranch=None, useHints=False, silentFail=False, highLowSwarm=None, maxMustHitStatement=None, progress=False, postCover=False, swarmLength=None, noCover=False, noEnumerateEnabled=False, full=True, swarmP=0.5, coverFile='coverage.out', markovP=1.0, swarmProbs=None, genDepth=None, exploitCeiling=0.1, logging=None, noCheck=False, throughput=False, uncaught=False, swarmSwitch=None, verbose=False, reducePool=False, exploit=None, fastQuickAnalysis=False, total=False, verboseExploit=False, swarm=True, sequenceP=1.0, biasLOC=None, timedProgress=30, relax=False, ddmin=False, stutter=None, readQuick=False, verboseActions=False, quickAnalysis=False, noReassign=False, sequenceSize=3, LOCProbs=False, sequencesFromTests=None, maxTests=-1, trackMaxCoverage=None, useQuickSequences=False, exploitBestHint=1, failedLogging=None, stopWhenStatements=None, greedyStutter=False, seed=None, stopWhenHitStatement=None, uniqueValuesAnalysis=False, normalize=False, startExploitStall=0, enumerateEnabled=False, internal=False, profile=False, multiple=True, stopWhenBranches=None, running=False, compareFails=False, Pcrossover=0.2, stopWhenHitBranch=None, depth=100, showActions=False)
TEST #69 STEP #5 (0:00:30.003682) Tue Nov 21 14:51:08 2017 [ 228 stmts 296 branches ] (no cov+ for 10 tests) 6805 TOTAL ACTIONS (226.805497509/s)
UNCAUGHT EXCEPTION
ERROR: (<type 'exceptions.OverflowError'>, OverflowError('date value out of range',), <traceback object at 0x10a1c4cb0>)
TRACEBACK:
  File "/Users/alex/tstl/examples/arrow/sut.py", line 405705, in safely
    act[2]()
  File "/Users/alex/tstl/examples/arrow/sut.py", line 31157, in act864
    self.p_time[5] = self.p_time[1].to(self.p_zone[4])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arrow/arrow.py", line 510, in to
    dt = self._datetime.astimezone(tz)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dateutil/tz/tz.py", line 667, in fromutc
    dt_out = dt + datetime.timedelta(seconds=tti.offset)
Original test has 14 steps

SAVING TEST AS failure.13887.test.0
FINAL VERSION OF TEST, WITH LOGGED REPLAY:
val0 = 0                                                                 # STEP 0
ACTION: val0 = 0 
val0 = None : <type 'NoneType'>
=> val0 = 0 : <type 'int'>
==================================================
locale4 =  u'fi'                                                         # STEP 1
ACTION: locale4 =  u'fi' 
locale4 = None : <type 'NoneType'>
=> locale4 = u'fi' : <type 'unicode'>
==================================================
locale3 =  u'nn'                                                         # STEP 2
ACTION: locale3 =  u'nn' 
locale3 = None : <type 'NoneType'>
=> locale3 = u'nn' : <type 'unicode'>
==================================================
time9 = arrow.get(val0)                                                  # STEP 3
ACTION: time9 = arrow.get(val0) 
val0 = 0 : <type 'int'>
time9 = None : <type 'NoneType'>
=> time9 = <Arrow [1970-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
time6 = time9.replace(seconds=val0)                                      # STEP 4
ACTION: time6 = time9.replace(seconds=val0) 
val0 = 0 : <type 'int'>
time9 = <Arrow [1970-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
time6 = None : <type 'NoneType'>
=> time6 = <Arrow [1970-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
val0 += 1                                                                # STEP 5
ACTION: val0 += 1 
val0 = 0 : <type 'int'>
=> val0 = 1 : <type 'int'>
==================================================
time1 = time9.replace(year=val0)                                         # STEP 6
ACTION: time1 = time9.replace(year=val0) 
val0 = 1 : <type 'int'>
time9 = <Arrow [1970-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
time1 = None : <type 'NoneType'>
=> time1 = <Arrow [0001-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
time5 = time9.replace(year=val0)                                         # STEP 7
ACTION: time5 = time9.replace(year=val0) 
val0 = 1 : <type 'int'>
time9 = <Arrow [1970-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
time5 = None : <type 'NoneType'>
=> time5 = <Arrow [0001-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
val0 += 1                                                                # STEP 8
ACTION: val0 += 1 
val0 = 1 : <type 'int'>
=> val0 = 2 : <type 'int'>
==================================================
time4 = time9.replace(year=val0)                                         # STEP 9
ACTION: time4 = time9.replace(year=val0) 
val0 = 2 : <type 'int'>
time9 = <Arrow [1970-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
time4 = None : <type 'NoneType'>
=> time4 = <Arrow [0002-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
time7 = time5.replace(seconds=val0)                                     # STEP 10
ACTION: time7 = time5.replace(seconds=val0) 
val0 = 2 : <type 'int'>
time5 = <Arrow [0001-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
time7 = None : <type 'NoneType'>
=> time7 = <Arrow [0001-01-01T00:00:02+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
time7.humanize(locale=locale4)                                          # STEP 11
ACTION: time7.humanize(locale=locale4) 
locale4 = u'fi' : <type 'unicode'>
time7 = <Arrow [0001-01-01T00:00:02+00:00]> : <class 'arrow.arrow.Arrow'>
==================================================
zone4 = 'US/Mountain'                                                   # STEP 12
ACTION: zone4 = 'US/Mountain'  
zone4 = None : <type 'NoneType'>
=> zone4 = 'US/Mountain' : <type 'str'>
==================================================
time5 = time1.to(zone4)                                                 # STEP 13
ACTION: time5 = time1.to(zone4) 
zone4 = 'US/Mountain' : <type 'str'>
time1 = <Arrow [0001-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
time5 = <Arrow [0001-01-01T00:00:00+00:00]> : <class 'arrow.arrow.Arrow'>
RAISED EXCEPTION: <type 'exceptions.OverflowError'> date value out of range
ERROR: (<type 'exceptions.OverflowError'>, OverflowError('date value out of range',), <traceback object at 0x10a1c4320>)
TRACEBACK:
  File "/Users/alex/tstl/examples/arrow/sut.py", line 405705, in safely
    act[2]()
  File "/Users/alex/tstl/examples/arrow/sut.py", line 31157, in act864
    self.p_time[5] = self.p_time[1].to(self.p_zone[4])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arrow/arrow.py", line 510, in to
    dt = self._datetime.astimezone(tz)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dateutil/tz/tz.py", line 667, in fromutc
    dt_out = dt + datetime.timedelta(seconds=tti.offset)
FAILURE IS NEW, STORING; NOW 1 DISTINCT FAILURES
STOPPING TEST DUE TO TIMEOUT, TERMINATED AT LENGTH 0
STOPPING TESTING DUE TO TIMEOUT
21.1492890995 PERCENT COVERED
60.2141218185 TOTAL RUNTIME
141 EXECUTED
13914 TOTAL TEST OPERATIONS
8.99208664894 TIME SPENT EXECUTING TEST OPERATIONS
50.2307598591 TIME SPENT EVALUATING GUARDS AND CHOOSING ACTIONS
0.00943398475647 TIME SPENT CHECKING PROPERTIES
9.0015206337 TOTAL TIME SPENT RUNNING SUT
0.135445594788 TIME SPENT RESTARTING
0.0 TIME SPENT REDUCING TEST CASES
1 FAILED
0 REPEATS OF FAILURES
1 ACTUAL DISTINCT FAILURES

FAILURE 0
val0 = 0                                                                 # STEP 0
locale4 =  u'fi'                                                         # STEP 1
locale3 =  u'nn'                                                         # STEP 2
time9 = arrow.get(val0)                                                  # STEP 3
time6 = time9.replace(seconds=val0)                                      # STEP 4
val0 += 1                                                                # STEP 5
time1 = time9.replace(year=val0)                                         # STEP 6
time5 = time9.replace(year=val0)                                         # STEP 7
val0 += 1                                                                # STEP 8
time4 = time9.replace(year=val0)                                         # STEP 9
time7 = time5.replace(seconds=val0)                                     # STEP 10
time7.humanize(locale=locale4)                                          # STEP 11
zone4 = 'US/Mountain'                                                   # STEP 12
time5 = time1.to(zone4)                                                 # STEP 13
ERROR: (<type 'exceptions.OverflowError'>, OverflowError('date value out of range',), <traceback object at 0x10a1c4320>)
TRACEBACK:
  File "/Users/alex/tstl/examples/arrow/sut.py", line 405705, in safely
    act[2]()
  File "/Users/alex/tstl/examples/arrow/sut.py", line 31157, in act864
    self.p_time[5] = self.p_time[1].to(self.p_zone[4])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arrow/arrow.py", line 510, in to
    dt = self._datetime.astimezone(tz)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/dateutil/tz/tz.py", line 667, in fromutc
    dt_out = dt + datetime.timedelta(seconds=tti.offset)
324 BRANCHES COVERED
246 STATEMENTS COVERED
